services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/Berdiali03/n8n
    branch: master
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: BeKa...33
      - key: WEBHOOK_URL
        value: https://your-subdomain.onrender.com/
